package com.carwatch.domain.schedule;

public enum CheckType {
    PZP_CHECK,
    COLLISION_INSURANCE_CHECK,
    STK_CHECK,
    EK_CHECK,
    VIGNETTE_SK_CHECK,
    VIGNETTE_CZ_CHECK,
    VIGNETTE_AT_CHECK,
    VIGNETTE_HU_CHECK,
    DAILY_SUMMARY_EMAIL,
    DAILY_REMINDER_SCAN
}
